### ISSUE TITLE
XSection EBeam Tool Error

### ISSUE THREAD

**Issue by nicteb** [SiEPIC/SiEPIC-Tools#212]
When trying to use the XSection tool on components from the EBeam library (v0.4.3), ANT components (v0.4.3), or SiN library (v0.4.3), the following error is displayed and no cross-section is shown:

![image](https://github.com/SiEPIC/SiEPIC-Tools/assets/91497171/733faca7-400d-4224-b240-5d9c6ae32ac3)

A blank new layout tab is opened titled [XSECTION] but is blank.

Windows, KLayout v0.29.1, python packages v1.2, siepic_tools v0.5.7, siepic_ebeam_pdk v0.4.9 (all up-to-date as of time of issue).

**Comment by lukasc-ubc** [comment]
Can you please upgrade SiEPIC-EBeam-PDK to v0.4.11 via the package manager?

After restarting KLayout, you should see the xsection menu with v 1.8 
<img width="444" alt="image" src="https://github.com/SiEPIC/SiEPIC-Tools/assets/15843200/40695bae-6fe6-4df9-86bd-46656d704425">

Then find the file EBeam/xsect/EBeam_ANT.xs

If the v 1.8 doesn't appear, it is because there are the old xsection files remaining from the v0.4.9 PDK.  The package manager doesn't delete files, only adds them...  If so, please remove:

 - EBeam/pymacros/xsection.lym
 - EBeam/pymacros/SiEPIC_xsection.lym
 
Then restart again.  If that doesn't solve it, please let me know.

Thanks
Lukas

**Comment by nicteb** [comment]
Yep, after upgrading v1.8 is available and I can successfully get the cross-section to display by running the .xs file!
The shortcut doesn't seem to work though:
![image](https://github.com/SiEPIC/SiEPIC-Tools/assets/91497171/526c6e85-1635-428b-b445-c0ff765c191c)

But the macro file is now appearing in the menu, so that helps!
![image](https://github.com/SiEPIC/SiEPIC-Tools/assets/91497171/bba0adb7-1ecc-4105-9a04-128090cb58f0)

**Comment by lukasc-ubc** [comment]
Indeed, I think it is a minor bug here: https://github.com/klayoutmatthias/xsection/issues/34
